from micropython import const
from bluetooth import UUID

SERVICE_UUID = UUID("12345678-1234-5678-1234-56789abcdef0")
COMMAND_UUID = UUID("12345678-1234-5678-1234-56789abcdef1")

_IO_CAPABILITY_DISPLAY_ONLY = const(0)
_IO_CAPABILITY_DISPLAY_YESNO = const(1)
_IO_CAPABILITY_KEYBOARD_ONLY = const(2)
_IO_CAPABILITY_NO_INPUT_OUTPUT = const(3)
_IO_CAPABILITY_KEYBOARD_DISPLAY = const(4)


IRQ_CENTRAL_CONNECT = const(1)
IRQ_CENTRAL_DISCONNECT = const(2)
IRQ_GATTS_WRITE = const(3)
IRQ_GATTS_READ_REQUEST = const(4)
IRQ_SCAN_RESULT = const(5)
IRQ_SCAN_DONE = const(6)
IRQ_PERIPHERAL_CONNECT = const(7)
IRQ_PERIPHERAL_DISCONNECT = const(8)
IRQ_GATTC_SERVICE_RESULT = const(9)
IRQ_GATTC_SERVICE_DONE = const(10)
IRQ_GATTC_CHARACTERISTIC_RESULT = const(11)
IRQ_GATTC_CHARACTERISTIC_DONE = const(12)
IRQ_GATTC_DESCRIPTOR_RESULT = const(13)
IRQ_GATTC_DESCRIPTOR_DONE = const(14)
IRQ_GATTC_READ_RESULT = const(15)
IRQ_GATTC_READ_DONE = const(16)
IRQ_GATTC_WRITE_DONE = const(17)
IRQ_GATTC_NOTIFY = const(18)
IRQ_GATTC_INDICATE = const(19)
IRQ_GATTS_INDICATE_DONE = const(20)
IRQ_MTU_EXCHANGED = const(21)
IRQ_L2CAP_ACCEPT = const(22)
IRQ_L2CAP_CONNECT = const(23)
IRQ_L2CAP_DISCONNECT = const(24)
IRQ_L2CAP_RECV = const(25)
IRQ_L2CAP_SEND_READY = const(26)
IRQ_CONNECTION_UPDATE = const(27)
IRQ_ENCRYPTION_UPDATE = const(28)
IRQ_GET_SECRET = const(29)
IRQ_SET_SECRET = const(30)


_GATTS_NO_ERROR = const(0x00)
_GATTS_ERROR_READ_NOT_PERMITTED = const(0x02)
_GATTS_ERROR_WRITE_NOT_PERMITTED = const(0x03)
_GATTS_ERROR_INSUFFICIENT_AUTHENTICATION = const(0x05)
_GATTS_ERROR_INSUFFICIENT_AUTHORIZATION = const(0x08)
_GATTS_ERROR_INSUFFICIENT_ENCRYPTION = const(0x0f)


_PASSKEY_ACTION_NONE = const(0)
_PASSKEY_ACTION_INPUT = const(2)
_PASSKEY_ACTION_DISPLAY = const(3)
_PASSKEY_ACTION_NUMERIC_COMPARISON = const(4)


_consts = {
    "IO": {
        "IO_CAPABILITY_DISPLAY_ONLY":_IO_CAPABILITY_DISPLAY_ONLY,
        "IO_CAPABILITY_DISPLAY_YESNO":_IO_CAPABILITY_DISPLAY_YESNO,
        "IO_CAPABILITY_KEYBOARD_ONLY":_IO_CAPABILITY_KEYBOARD_ONLY,
        "IO_CAPABILITY_NO_INPUT_OUTPUT":_IO_CAPABILITY_NO_INPUT_OUTPUT,
        "IO_CAPABILITY_KEYBOARD_DISPLAY":_IO_CAPABILITY_KEYBOARD_DISPLAY,
    },
    "IRQ": {
        "IRQ_CENTRAL_CONNECT": IRQ_CENTRAL_CONNECT,
        "IRQ_CENTRAL_DISCONNECT": IRQ_CENTRAL_DISCONNECT,
        "IRQ_GATTS_WRITE": IRQ_GATTS_WRITE,
        "IRQ_GATTS_READ_REQUEST": IRQ_GATTS_READ_REQUEST,
        "IRQ_SCAN_RESULT": IRQ_SCAN_RESULT,
        "IRQ_SCAN_DONE": IRQ_SCAN_DONE,
        "IRQ_PERIPHERAL_CONNECT": IRQ_PERIPHERAL_CONNECT,
        "IRQ_PERIPHERAL_DISCONNECT": IRQ_PERIPHERAL_DISCONNECT,
        "IRQ_GATTC_SERVICE_RESULT": IRQ_GATTC_SERVICE_RESULT,
        "IRQ_GATTC_SERVICE_DONE": IRQ_GATTC_SERVICE_DONE,
        "IRQ_GATTC_CHARACTERISTIC_RESULT": IRQ_GATTC_CHARACTERISTIC_RESULT,
        "IRQ_GATTC_CHARACTERISTIC_DONE": IRQ_GATTC_CHARACTERISTIC_DONE,
        "IRQ_GATTC_DESCRIPTOR_RESULT": IRQ_GATTC_DESCRIPTOR_RESULT,
        "IRQ_GATTC_DESCRIPTOR_DONE": IRQ_GATTC_DESCRIPTOR_DONE,
        "IRQ_GATTC_READ_RESULT": IRQ_GATTC_READ_RESULT,
        "IRQ_GATTC_READ_DONE": IRQ_GATTC_READ_DONE,
        "IRQ_GATTC_WRITE_DONE": IRQ_GATTC_WRITE_DONE,
        "IRQ_GATTC_NOTIFY": IRQ_GATTC_NOTIFY,
        "IRQ_GATTC_INDICATE": IRQ_GATTC_INDICATE,
        "IRQ_GATTS_INDICATE_DONE": IRQ_GATTS_INDICATE_DONE,
        "IRQ_MTU_EXCHANGED": IRQ_MTU_EXCHANGED,
        "IRQ_L2CAP_ACCEPT": IRQ_L2CAP_ACCEPT,
        "IRQ_L2CAP_CONNECT": IRQ_L2CAP_CONNECT,
        "IRQ_L2CAP_DISCONNECT": IRQ_L2CAP_DISCONNECT,
        "IRQ_L2CAP_RECV": IRQ_L2CAP_RECV,
        "IRQ_L2CAP_SEND_READY": IRQ_L2CAP_SEND_READY,
        "IRQ_CONNECTION_UPDATE": IRQ_CONNECTION_UPDATE,
        "IRQ_ENCRYPTION_UPDATE": IRQ_ENCRYPTION_UPDATE,
        "IRQ_GET_SECRET": IRQ_GET_SECRET,
        "IRQ_SET_SECRET": IRQ_SET_SECRET,
    },
    "GATTS": {
        "GATTS_NO_ERROR": _GATTS_NO_ERROR,
        "GATTS_ERROR_READ_NOT_PERMITTED": _GATTS_ERROR_READ_NOT_PERMITTED,
        "GATTS_ERROR_WRITE_NOT_PERMITTED": _GATTS_ERROR_WRITE_NOT_PERMITTED,
        "GATTS_ERROR_INSUFFICIENT_AUTHENTICATION": _GATTS_ERROR_INSUFFICIENT_AUTHENTICATION,
        "GATTS_ERROR_INSUFFICIENT_AUTHORIZATION": _GATTS_ERROR_INSUFFICIENT_AUTHORIZATION,
        "GATTS_ERROR_INSUFFICIENT_ENCRYPTION": _GATTS_ERROR_INSUFFICIENT_ENCRYPTION,
    },
    "PASSKEY": {
        "PASSKEY_ACTION_NONE": _PASSKEY_ACTION_NONE,
        "PASSKEY_ACTION_INPUT": _PASSKEY_ACTION_INPUT,
        "PASSKEY_ACTION_DISPLAY": _PASSKEY_ACTION_DISPLAY,
        "PASSKEY_ACTION_NUMERIC_COMPARISON": _PASSKEY_ACTION_NUMERIC_COMPARISON,
    }
}

def get_name(category:str, code:int) -> str:
    try:
        return list(_consts[category].keys())[list(_consts[category].values()).index(code)]
    except:
        return "UNKNOWN"