listener 8883
protocol mqtt

cafile   /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile  /mosquitto/certs/server.key

require_certificate false

# Ingen anonym adgang
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file      /mosquitto/config/acl
